const base=[  {
    type: 'input',
    component: 'DwInput',
    name: '单行文本',
    icon: 'icon-input',
    options: {
        width: '100%',
        isLabelWidth: false,
        labelWidth: 100,
        hideLabel: false,
        defaultValue: '',
        placeholder: '',
        customClass: '',
        disabled: false,
        readonly: false,
        showPassword: false,
        required: false,
        requiredMessage: '',
        isPattern: false,
        pattern: '',
        patternMessage: '',
        isType: false,
        type: '',
        typeMessage: '',
    },
},
    {
        type: 'textarea',
        component: 'DwTextarea',
        name: '多行文本',
        icon: 'icon-textarea',
        options: {
            width: '100%',
            isLabelWidth: false,
            labelWidth: 100,
            hideLabel: false,
            defaultValue: '',
            placeholder: '',
            customClass: '',
            disabled: false,
            readonly: false,
            required: false,
            requiredMessage: '',
            isPattern: false,
            pattern: '',
            patternMessage: '',
        },
    },
    {
        type: 'number',
        component: 'DwNumber',
        name: '计数器',
        icon: 'icon-number',
        options: {
            width: '',
            isLabelWidth: false,
            labelWidth: 100,
            hideLabel: false,
            defaultValue: 0,
            min: 1,
            max: 99,
            step: 1,
            customClass: '',
            controlsPosition: 'default',
            disabled: false,
            required: false,
            requiredMessage: '',
        },
    }
]


export {base};
